source :gemcutter
gem 'rails' , '2.3.11'
gem 'sqlite3'
gem 'clickatell'
gem 'json'
gem 'facebooker2'
gem 'paypal_adaptive'
gem 'ruby_core_source'
gem 'heroku'
gem 'taps'
gem 'ruby-debug-base19'
gem 'ruby-debug19'
gem 'ruby-debug-ide19'
